---
- hosts: all
  gather_facts: yes
  tasks:
    - name: Check Azure Arc agent version on Linux
      command: "azcmagent version"
      register: linux_arc_version_before
      when: ansible_os_family != "Windows"

    - name: Check Azure Arc agent version on Windows
      win_command: "C:\\Program Files\\AzureConnectedMachineAgent\\azcmagent.exe version"
      register: windows_arc_version_before
      when: ansible_os_family == "Windows"

    - name: Save Linux version to file
      lineinfile:
        path: "/tmp/beforeupdate"
        line: "{{ inventory_hostname }} - {{ linux_arc_version_before.stdout }}"
        create: yes
      delegate_to: localhost
      when: ansible_os_family != "Windows"

    - name: Save Windows version to file
      lineinfile:
        path: "/tmp/beforeupdate"
        line: "{{ inventory_hostname }} - {{ windows_arc_version_before.stdout }}"
        create: yes
      delegate_to: localhost
      when: ansible_os_family == "Windows"

    - name: Update Azure Arc agent on Debian/Ubuntu
      apt:
        name: azcmagent
        state: latest
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Update Azure Arc agent on RedHat/CentOS
      yum:
        name: azcmagent
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Update Azure Arc agent on Windows
      win_shell: |
        "C:\\Program Files\\AzureConnectedMachineAgent\\azcmagent.exe" upgrade
      when: ansible_os_family == "Windows"

    - name: Check Azure Arc agent version on Linux after update
      command: "azcmagent version"
      register: linux_arc_version_after
      when: ansible_os_family != "Windows"

    - name: Check Azure Arc agent version on Windows after update
      win_command: "C:\\Program Files\\AzureConnectedMachineAgent\\azcmagent.exe version"
      register: windows_arc_version_after
      when: ansible_os_family == "Windows"

    - name: Save Linux version to file after update
      lineinfile:
        path: "/tmp/afterupdate"
        line: "{{ inventory_hostname }} - {{ linux_arc_version_after.stdout }}"
        create: yes
      delegate_to: localhost
      when: ansible_os_family != "Windows"

    - name: Save Windows version to file after update
      lineinfile:
        path: "/tmp/afterupdate"
        line: "{{ inventory_hostname }} - {{ windows_arc_version_after.stdout }}"
        create: yes
      delegate_to: localhost
      when: ansible_os_family == "Windows"
